apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 12.7.3
    helm:
      values: |
        mode: standalone
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin123
        defaultBuckets: mlflow-artifacts
        persistence:
          enabled: true
          size: 10Gi
        service:
          type: ClusterIP
          port: 9000
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
